# Generated by Django 4.2 on 2025-09-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'verbose_name': 'Customer Account', 'verbose_name_plural': 'Customer Accounts'},
        ),
    ]
