"""
Django settings for bloomberry project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Autor: Maria Clara Medina Gomez
# Proyecto: BloomBerry
# Archivo: settings.py
# Descripción: Configuración principal de Django para BloomBerry (MVT, i18n, static, templates, DB).

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'dev-secret-key'   # luego hay que moverlas a variables de entorno 
DEBUG = True
ALLOWED_HOSTS = []

# APPS
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'users',
    'products',
    'orders',
    'payments',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bloomberry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # Todas las plantillas del proyecto van aquí (regla: vistas extienden base.html)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bloomberry.wsgi.application'

#Base de datos 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# INTERNACIONALIZACIÓN 
LANGUAGE_CODE = 'es'          
TIME_ZONE = 'America/Bogota'             
USE_I18N = True
USE_TZ = True

# Donde estarán los .po/.mo ( requisito "resources/lang/*")
from pathlib import Path
LOCALE_PATHS = [BASE_DIR / 'resources' / 'lang']

# STATIC & MEDIA
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']       # assets para desarrollo
STATIC_ROOT = BASE_DIR / 'staticfiles'         # para collectstatic en despliegue

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# LOGIN (secciones: usuario final vs admin)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'products:home'           # ruta pública principal
LOGOUT_REDIRECT_URL = 'products:home'

# Si se usará usuario custom más adelante:
# AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email de desarrollo (útil para reseteo de contraseña sin SMTP real)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
